[project]
name = "unir"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datetime>=6.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "numpy",
    "pandas",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.6",
]
